development:
  adapter: postgresql
  encoding: unicode
  database: LoLSite_development
  pool: 5
  username: damiano
  password: pp34wf
  host: localhost
  
test:
  adapter: postgresql
  encoding: unicode
  database: LoLSite_test
  pool: 5
  username: damiano  
  password: pp34wf
  host: localhost