development:
  adapter: postgresql
  encoding: unicode
  database: lolSite_development
  pool: 5
  username: dany
  password: pp34wf
  host: localhost
  
test:
  adapter: postgresql
  encoding: unicode
  database: lolSite_test
  pool: 5
  username: dany  
  password: pp34wf
  host: localhost