development:
  adapter: postgresql
  encoding: unicode
  database: lol_dev
  pool: 5
  username: postgres
  password: postgres
  host: localhost
  
test:
  adapter: postgresql
  encoding: unicode
  database: lol_test
  pool: 5
  username: postgres
  password: postgres
  host: localhost