











#
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
# Examples:
# Item.create(name: "", info:"", image:"items/")
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
# This file should contain all the record creation needed to seed the database with its default values.
#Champions
#items
Champion.create(name: 'Aatrox', lane: 'top, jungle', quickinfo: 'Has a passiv to revive himself and strongly depends on autohits', portrait: 'Portrait/Aatrox_Square_0.png', splashart:'Splashart/Aatrox_0.jpg', splashartBig:'Splashart/Aatrox_Splash_0.jpg')
Champion.create(name: 'Ahri',lane: 'mid', quickinfo: 'A strong midlaner with: Poke, escape, cc and roam potential', portrait: 'Portrait/Ahri_Square_0.png', splashart:'Splashart/Ahri_0.jpg', splashartBig:'Splashart/Ahri_Splash_0.jpg')
Champion.create(name: 'Akali',lane: 'mid/top', quickinfo: 'Assasin', portrait: 'Portrait/Akali_Square_0.png', splashart:'Splashart/Akali_0.jpg', splashartBig:'Splashart/Akali_Splash_0.jpg')
Champion.create(name: 'Alistar',lane: 'sup/jungle', quickinfo: 'Tank and CC heavy', portrait: 'Portrait/Alistar_Square_0.png', splashart:'Splashart/Alistar_0.jpg', splashartBig:'Splashart/Alistar_Splash_0.jpg')
Champion.create(name: 'Amumu',lane: 'jungle', quickinfo: 'Great AOE CC and Tanky', portrait: 'Portrait/Amumu_Square_0.png', splashart:'Splashart/Amumu_0.jpg', splashartBig:'Splashart/Amumu_Splash_0.jpg')
Champion.create(name: 'Anivia',lane: 'mid', quickinfo: 'Nice Burst and survive passiv', portrait: 'Portrait/Anivia_Square_0.png', splashart:'Splashart/Anivia_0.jpg', splashartBig:'Splashart/Anivia_Splash_0.jpg')
Champion.create(name: 'Annie',lane: 'mid/sup', quickinfo: 'Insane Burst and nice cc mechanics. Strong initator', portrait: 'Portrait/Annie_Square_0.png', splashart:'Splashart/Annie_0.jpg', splashartBig:'Splashart/Annie_Splash_0.jpg')
Champion.create(name: 'Ashe',lane: 'adc', quickinfo: 'Global ult, great kite potential', portrait: 'Portrait/Ashe_Square_0.png', splashart:'Splashart/Ashe_0.jpg', splashartBig:'Splashart/Ashe_Splash_0.jpg')
Champion.create(name: 'Azir',lane: 'mid', quickinfo: 'Unique Mage with high dmg during all game phases', portrait: 'Portrait/Azir_Square_0.png', splashart:'Splashart/Azir_0.jpg', splashartBig:'Splashart/Azir_Splash_0.jpg')
Champion.create(name: 'Blitzcrank',lane: 'sup', quickinfo: 'CC heavy support with a grap', portrait: 'Portrait/Blitzcrank_Square_0.png', splashart:'Splashart/Blitzcrank_0.jpg', splashartBig:'Splashart/Blitzcrank_Splash_0.jpg')
Champion.create(name: 'Brand',lane:'mid/sup', quickinfo:'Immobile Mage with high Burst/AOE Damage', portrait:'Portrait/Brand_Square_0.png', splashart:'Splashart/Brand_0.jpg', splashartBig:'Splashart/Brand_Splash_0.jpg')
Champion.create(name: 'Braum',lane:'sup', quickinfo:'CC/Tank Support with strong peel', portrait: 'Portrait/Braum_Square_0.png', splashart:'Splashart/Braum_0.jpg', splashartBig:'Splashart/Braum_Splash_0.jpg')
Champion.create(name: 'Caitlyn',lane:'adc', quickinfo:'Long range adc with minimal mobility, lane bully', portrait:'Portrait/Caitlyn_Square_0.png', splashart:'Splashart/Caitlyn_0.jpg', splashartBig:'Splashart/Caitlyn_Splash_0.jpg')
Champion.create(name: 'Cassiopeia',lane:'mid', quickinfo:'High DPS Mage with an AOE CC Ultimate', portrait:'Portrait/Cassiopeia_Square_0.png', splashart:'Splashart/Cassiopeia_0.jpg', splashartBig:'Splashart/Cassiopeia_Splash_0.jpg')
Champion.create(name: 'Chogath',lane:'top,mid,jungle', quickinfo:'Tank with alot of CC and true dmg Ultimate, high AP ratios', portrait: 'Portrait/Chogath_Square_0.png', splashart:'Splashart/Chogath_0.jpg', splashartBig:'Splashart/Chogath_Splash_0.jpg')
Champion.create(name: 'Corki',lane:'adc', quickinfo:'Midgame adc with high burst and poke, high portion of magic dmg on his abilities', portrait: 'Portrait/Corki_Square_0.png', splashart:'Splashart/Corki_0.jpg', splashartBig:'Splashart/Corki_Splash_0,jpg')
Champion.create(name: 'Darius',lane:'top/jungle', quickinfo:'High dmg bruiser with an execute Ultimate that resets', portrait: 'Portrait/Darius_Square_0.png', splashart:'Splashart/Darius_0.jpg', splashartBig:'Splashart/Darius_Splash_0.jpg')
Champion.create(name: 'Diana',lane:'mid/jungle', quickinfo:'Mage with strong gapcloser, can build full dmg for high burst or tanky bruiser', portrait: 'Portrait/Diana_Square_0.png', splashart:'Splashart/Diana_0.jpg', splashartBig:'Splashart/Diana_Splash_0.jpg')
Champion.create(name: 'Draven',lane:'adc', quickinfo:'Adc with Unique abilitiy to maximize his dmg, strong snowballing potential', portrait: 'Portrait/Draven_Square_0.png', splashart:'Splashart/Draven_0.jpg', splashartBig:'Splashart/Draven_Splash_0.jpg')
Champion.create(name: 'DrMundo',lane:'top/jungle', quickinfo:'Tank that scales with HP and has high regeneration', portrait: 'Portrait/DrMundo_Square_0.png', splashart:'Splashart/DrMundo_0.jpg', splashartBig:'Splashart/DrMundo_Splash_0.jpg')
Champion.create(name: 'Elise',lane:'top/jungle', quickinfo:'Shapeshifting Champion with 7 abilities. Has %-dmg on max health', portrait:'Portrait/Elise_Square_0.png', splashart:'Splashart/Elise_0.jpg', splashartBig:'Splashart/Elise_Splash_0.jpg')
Champion.create(name: 'Evelynn',lane:'jungle', quickinfo:'Unique stealth mechanic forces the enemy team to heavily invest into Pink Wards to feel safe', portrait:'Portrait/Evelynn_Square_0.png', splashart:'Splashart/Evelynn_0.jpg', splashartBig:'Splashart/Evelynn_Splash_0.jpg')
Champion.create(name: 'Ezreal',lane:'adc/mid', quickinfo:'High mobile adc with a global Ultimate, strong poke and AP-ratios enables him to be played as mage', portrait:'Portrait/Ezreal_Square_0.png', splashart:'Splashart/Ezreal_0.jpg', splashartBig:'Splashart/Ezreal_Splash_0.jpg')
Champion.create(name: 'Fiddlesticks', lane:'jungle/support', quickinfo:'Frontline mage with strong CC and high sustain', portrait:'Portrait/Fiddlesticks_Square_0.png', splashart:'Splashart/Fiddlesticks_0.jpg', splashartBig:'Splashart/Fiddlesticks_Splash_0.jpg')
Champion.create(name: 'Fiora',lane:'top/mid', quickinfo:'Melee Carry, good duelist. Can be picked mid in some matchups as hardcounter', portrait:'Portrait/Fiora_Square_0.png', splashart:'Splashart/Fiora_0.jpg', splashartBig:'Splashart/Fiora_Splash_0.jpg')
Champion.create(name: 'Fizz',lane:'top/mid/jungle', quickinfo:'High mobility and overall strong kit with high outplay potential', portrait:'Portrait/Fizz_Square_0.png', splashart:'Splashart/Fizz_0.jpg', splashartBig:'Splashart/Fizz_Splash_0.jpg')
Champion.create(name: 'Galio',lane:'top/mid/support', quickinfo:'High utility and CC ultimate make him versatile. His Anti Mage Passive lets him counterpick midlaners', portrait:'Portrait/Galio_Square_0.png', splashart:'Splashart/Galio_0.jpg', splashartBig:'Splashart/Galio_Splash_0.jpg')
Champion.create(name: 'Gangplank',lane:'top/mid', quickinfo:'Pirate with poke that procs on-hit effects and utility for his team', portrait:'Portrait/Gangplank_Square_0.png', splashart:'Splashart/Gangplank_0.jpg', splashartBig:'Splashart/Gangplank_Splash_0.jpg')
Champion.create(name: 'Garen', lane:'top', quickinfo:'Lane bully with regeneration passive and execute ultimate', portrait:'Portrait/Garen_Square_0.png', splashart:'Splashart/Garen_0.jpg', splashartBig:'Splashart/Garen_Splash_0.jpg')
Champion.create(name: 'Gnar', lane:'top', quickinfo:'Shapeshifter with a squishy dps form and a tanky bruiser form', portrait:'Portrait/Gnar_Square_0.png', splashart:'Splashart/Gnar_0.jpg', splashartBig:'Splashart/Gnar_Splash_0.jpg')
Champion.create(name: 'Gragas', lane:'mid/top/support/jungle', quickinfo:'Damage reduction and alot of CC in his Kit make him a versatile pick for every role besides adc', portrait:'Portrait/Gragas_Square_0.png',splashart:'Splashart/Gragas_0.jpg', splashartBig:'Splashart/Gragas_Splash_0.jpg')
Champion.create(name: 'Graves', lane:'adc', quickinfo:'His short range is offset by his tanky passive and his high burst', portrait:'Portrait/Graves_Square_0.png', splashart:'Splashart/Graves_0.jpg', splashartBig:'Splashart/Graves_Splash_0.jpg')
Champion.create(name: 'Hecarim', lane:'top/jungle', quickinfo:'Bruiser with high base dmg and strong engage', portrait:'Portrait/Hecarim_Square_0.png', splashart:'Splashart/Hecarim_0.jpg', splashartBig:'Splashart/Hecarim_Splash_0.jpg')
Champion.create(name: 'Heimerdinger', lane:'mid/top', quickinfo:'Summons turrets to help him fight, high siege potential', portrait:'Portrait/Heimerdinger_Square_0.png', splashart:'Splashart/Heimerdinger_0.jpg', splashartBig:'Splashart/Heimerdinger_Splash_0.jpg')
Champion.create(name: 'Irelia', lane:'top', quickinfo:'Bruiser with high sustain and dmg, her passive makes it almost impossible to CC her', portrait:'Portrait/Irelia_Square_0.png', splashart:'Splashart/Irelia_0.jpg', splashartBig:'Splashart/Irelia_Splash_0.jpg')
Champion.create(name: 'Janna', lane:'support', quickinfo:'One of the strongest disengage supports in the game, very good in combination with immobile adc', portrait:'Portrait/Janna_Square_0.png', splashart:'Splashart/Janna_0.jpg', splashartBig:'Splashart/Janna_Splash_0.jpg')
Champion.create(name: 'JarvanIV', lane:'mid/top/jungle', quickinfo:'All round strong ad bruiser with good engage and tanky/dmg depending on the build', portrait:'Portrait/JarvanIV_Square_0.png', splashart:'Splashart/JarvanIV_0.jpg', splashartBig:'Splashart/JarvanIV_Splash_0.jpg')
Champion.create(name: 'Jax', lane:'top/jugnle', quickinfo:'One of the strongest lategame bruiser with his high mixed dmg dps, his ultimate gives him defensive stats which enables him to build alot of dmg', portrait:'Portrait/Jax_Square_0.png', splashart:'Splashart/Jax_0.jpg', splashartBig:'Splashart/Jax_Splash_0.jpg')
Champion.create(name: 'Jayce', lane:'top/mid/adc', quickinfo:'Can change between melee and range form. Strong poke, high burst, depending on his form', portrait:'Portrait/Jayce_Square_0.png', splashart:'Splashart/Jayce_0.jpg', splashartBig:'Splashart/Jayce_Splash_0.jpg')
Champion.create(name: 'Jinx', lane:'adc', quickinfo:'Long range AOE autohits or short range which build up attackspeed. Execute global ult with a reset passive that speeds her up on every kill/assist make her one of the strongest adc', portrait:'Portrait/Jinx_Square_0.png', splashart:'Splashart/Jinx_0.jpg', splashartBig:'Splashart/Jinx_Splash_0.jpg')
Champion.create(name: 'Karma', lane:'mid/sup', quickinfo:'Dmg on every ability and good utility make her playable in midlane or as support. Unique Ultimate which enhances every other ability', portrait:'Portrait/Karma_Square_0.png', splashart:'Splashart/Karma_0.jpg', splashartBig:'Splashart/Karma_Splash_0.jpg')
Champion.create(name: 'Karthus', lane:'mid', quickinfo:'Mage with a global ult which cannot be avoided besides with items/spells that make someone invulnerable or spellshields/banshees veil', portrait:'Portrait/Karthus_Square_0.png', splashart:'Splashart/Karthus_0.jpg', splashartBig:'Splashart/Karthus_Splash_0.jpg')
Champion.create(name: 'Kassadin', lane:'mid/top', quickinfo:'Mage with strong lategame because of his ultimate that works like the summoner spell flash on a 5 sec cooldown', portrait:'Portrait/Kassadin_Square_0.png', splashart:'Splashart/Kassadin_0.jpg', splashartBig:'Splashart/Kassadin_Splash_0.jpg')
Champion.create(name: 'Katarina', lane:'mid', quickinfo:'Assassin with a passive that resets her skills cooldown on kill/assist', portrait:'Portrait/Katarina_Square_0.png', splashart:'Splashart/Katarina_0.jpg', splashartBig:'Splashart/Katarina_Splash_0.jpg')
Champion.create(name: 'Kayle', lane:'mid/top', quickinfo:'Mage that can enhance her autohits and dish out some serious dps. Ontop of that she has strong utility, with an ultimate that makes any ally champion invulnerable', portrait:'Portrait/Kayle_Square_0.png', splashart:'Splashart/Kayle_0.jpg', splashartBig:'Splashart/Kayle_Splash_0.jpg')
Champion.create(name: 'Kennen', lane:'mid/top', quickinfo:'Mage who stuns any champion he hits 3 times. AOE ultimate for potential 5 man stuns makes him strong in engange Team compositions', portrait:'Portrait/Kennen_Square_0.png', splashart:'Splashart/Kennen_0.jpg', splashartBig:'Splashart/Kennen_Splash_0.jpg')
Champion.create(name: 'Khazix', lane:'top/jungle', quickinfo:'Assassin which can evolve his abilities on lvl 6/11/16 to adapt his playstyle', portrait:'Portrait/Khazix_Square_0.png', splashart:'Splashart/Khazix_0.jpg', splashartBig:'Splashart/Khazix_Splash_0.jpg')
Champion.create(name: 'KogMaw', lane:'mid/adc', quickinfo:'Long range and % of max health dmg on hit make him one of the deadliest adc. AP-ratios on his abilities make him playable mid as poke mage with his spammable ultimate', portrait:'Portrait/KogMaw_Square_0.png', splashart:'Splashart/KogMaw_0.jpg', splashartBig:'Splashart/KogMaw_Splash_0.jpg')
Champion.create(name: 'Leblanc', lane:'mid', quickinfo:'Mage with high mobility and burst dmg. Passive creates a double when she gets low hp, enables alot of outplays', portrait:'Portrait/Leblanc_Square_0.png', splashart:'Splashart/Leblanc_0.jpg', splashartBig:'Splashart/Leblanc_Splash_0.jpg')
Champion.create(name: 'LeeSin', lane:'mid/top/jungle', quickinfo:'High mobile bruiser with 7 abilities, can build tanky because of his utiliy on his abilities or full dmg as ad caster to blow people up', portrait:'Portrait/LeeSin_Square_0.png', splashart:'Splashart/LeeSin_0.jpg', splashartBig:'Splashart/LeeSin_Splash_0.jpg')
Champion.create(name: 'Leona', lane:'support', quickinfo:'Tank support with alot of CC and strong engage', portrait:'Portrait/Leona_Square_0.png', splashart:'Splashart/Leona_0.jpg', splashartBig:'Splashart/Leona_Splash_0.jpg')
Champion.create(name: 'Lissandra', lane:'mid/top', quickinfo:'Mage with a ultimate to freeze an enemy or himself to gain invulnerability', portrait:'Portrait/Lissandra_Square_0.png', splashart:'Splashart/Lissandra_0.jpg', splashartBig:'Splashart/Lisanndra_Splash_0.jpg')
Champion.create(name: 'Lucian', lane:'adc', quickinfo:'Adc with a short range but a passive that enables him to shoot twice after using an ability for high burst dmg', portrait:'Portrait/Lucian_Square_0.png', splashart:'Splashart/Lucian_0.jpg', splashartBig:'Splashart/Lucian_Splash_0.jpg')
Champion.create(name: 'Lulu', lane:'mid/top/support', quickinfo:'Mage with high utility, cc and decent dmg make her a versatile pick in multiple lanes', portrait:'Portrait/Lulu_Square_0.png', splashart:'Splashart/Lulu_0.jpg', splashartBig:'Splashart/Lulu_Splash_0.jpg')
Champion.create(name: 'Lux', lane:'mid/support', quickinfo:'Long range mage with high AOE dmg and some utility and cc', portrait:'Portrait/Lux_Square_0.png', splashart:'Splashart/Lux_0.jpg', splashartBig:'Splashart/Lux_Splash_0.jpg')
Champion.create(name: 'Malphite', lane:'mid/top', quickinfo:'Tank with strong initiation. AP-ratios on his abilites make him playable as a burst mage', portrait:'Portrait/Malphite_Square_0.png', splashart:'Splashart/Malphite_0.jpg', splashartBig:'Splashart/Malphite_Splash_0.jpg')
Champion.create(name: 'Malzahar', lane:'mid', quickinfo:'Mage with high pushing power and an ultimate to hold a single target in place', portrait:'Portrait/Malzahar_Square_0.png', splashart:'Splashart/Malzahar_0.jpg', splashartBig:'Splashart/Malzahar_Splash_0.jpg')
Champion.create(name: 'Maokai', lane:'top/jungle', quickinfo:'Tank with good CC and an ulimate to reduce dmg for his whole team in an area around him', portrait:'Portrait/Maokai_Square_0.png', splashart:'Splashart/Maokai_0.jpg', splashartBig:'Splashart/Maokai_Splash_0.jpg')
Champion.create(name: 'MasterYi', lane:'jungle', quickinfo:'Melee carry with an ultimate that makes him immune to slows and refreshes his cooldowns on kills/assists', portrait:'Portrait/MasterYi_Square_0.png', splashart:'Splashart/Masteryi_0.jpg', splashartBig:'Splashart/Masteryi_Splash_0.jpg')
Champion.create(name: 'MissFortune', lane:'adc', quickinfo:'ADC with a movementspeed passive and an aoe ultimate which wrecks every enemy infront of her', portrait:'Portrait/MissFortune_Square_0.png', splashart:'Splashart/MissFortune_0.jpg', splashartBig:'Splashart/MissFortune_Splash_0.jpg')
Champion.create(name: 'Mordekaiser', lane:'top', quickinfo:'AP bruiser that uses his health as resource for his abilities and in return gets a shield for the amount of dmg he dishes out. If he kills an enemy with his ultimate on him, he creates a ghost of the enemy which he can control', portrait:'Portrait/Mordekaiser_Square_0.png', splashart:'Splashart/Mordekaiser_0.jpg', splashartBig:'Splashart/Morderkaiser_Splash_0.jpg')
Champion.create(name: 'Morgana', lane:'mid/support', quickinfo:'AP mage with strong cc. Has a shield that prevents magic dmg and any form of CC which ontop of her own CC make her an excellent support', portrait:'Portrait/Morgana_Square_0.png', splashart:'Splashart/Morgana_0.jpg', splashartBig:'Splashart/Morgana_Splash_0.jpg')
Champion.create(name: 'Nami', lane:'support', quickinfo:'Support mage with cc, disengage ultimate and a heal', portrait:'Portrait/Nami_Square_0.png', splashart:'Splashart/Nami_0.jpg', splashartBig:'Splashart/Nami_Splash_0.jpg')
Champion.create(name: 'Nasus', lane:'top', quickinfo:'Bruiser whose dmg scales with minion kills', portrait:'Portrait/Nasus_Square_0.png', splashart:'Splashart/Nasus_0.jpg', splashartBig:'Splashart/Nasus_Splash_0.jpg')
Champion.create(name: 'Nautilus', lane:'jungle', quickinfo:'Tank bruiser with alot of CC and a hook for deadly ganks', portrait:'Portrait/Nautilus_Square_0.png', splashart:'Splashart/Nautilus_0.jpg', splashartBig:'Splashart/Nautilus_Splash_0.jpg')
Champion.create(name: 'Nidalee', lane:'top/mid/jungle', quickinfo:'Shapeshifter with strong poke and chase to hunt her enemies down once their low', portrait:'Portrait/Nidalee_Square_0.png', splashart:'Splashart/Nidalee_0.jpg', splashartBig:'Splashart/Nidalee_Splash_0.jpg')
Champion.create(name: 'Nocturne', lane:'jungle', quickinfo:'High dmg bruiser with a strong lvl 6 gank and a spellshield that gives him attackspeed', portrait:'Portrait/Nocturne_Square_0.png', splashart:'Splashart/Nocturne_0.jpg', splashartBig:'Splashart/Nocturne_Splash_0.jpg') 
Champion.create(name: 'Nunu', lane:'jungle/support', quickinfo:'Tank bruiser with a strong disengage ultimate and utility that enables him to be played as support aswell. Is able to consue minions/monster for high jugnle sustain', portrait:'Portrait/Nunu_Square_0.png', splashart:'Splashart/Nunu_0.jpg', splashartBig:'Splashart/Nunu_Splash_0.jpg')
Champion.create(name: 'Olaf', lane:'top/jungle', quickinfo:'AD Bruiser that attacks faster and gains lifesteal based on his missing HP', portrait:'Portrait/Olaf_Square_0.png', splashart:'Splashart/Olaf_0.jpg', splashartBig:'Splashart/Olaf_Splash_0.jpg')
Champion.create(name: 'Orianna', lane:'mid', quickinfo:'AP mage with high zone control and an ultimate that cam be used to engage or disengage', portrait:'Portrait/Orianna_Square_0.png', splashart:'Splashart/Orianna_0.jpg', splashartBig:'Splashart/Orianna_Splash_0.jpg')
Champion.create(name: 'Pantheon', lane:'top/mid/jungle', quickinfo:'AD caster with a passive that can block autohits from enemy champions or monsters. Global ultimate for strong ganks / engages', portrait:'Portrait/Pantheon_Square_0.png', splashart:'Splashart/Pantheon_0.jpg', splashartBig:'Splashart/Pantheon_Splash_0.jpg')
Champion.create(name: 'Poppy', lane:'jungle/top', quickinfo:'Can be played as ap or ad bruiser with high burst and an ultimate which greatly reduces incoming dmg', portrait:'Portrait/Poppy_Square_0.png', splashart:'Splashart/Poppy_0.jpg', splashartBig:'Splashart/Poppy_Splash_0.jpg')
Champion.create(name: 'Quinn', lane:'adc/top', quickinfo:'Adc with high mobility and a Shapeshifting ultimate which acts as an aoe execute once it ends. Her strong splitpush and ganks make her playable as toplaner', portrait:'Portrait/Quinn_Square_0.png', splashart:'Splashart/Quinn_0.jpg', splashartBig:'Splashart/Quinn_Splash_0.jpg')
Champion.create(name: 'Rammus', lane:'jungle', quickinfo:'High movementspeed with his ability and a taunt for scary early ganks. Strong lategame tank', portrait:'Portrait/Rammus_Square_0.png', splashart:'Splashart/Rammus_0.jpg', splashartBig:'Splashart/Rammus_Splash_0.jpg')
Champion.create(name: 'RekSai', lane:'jungle', quickinfo:'Global ultimate and high regeneration passive for goodjungle sustain', portrait:'Portrait/RekSai_Square_0.png', splashart:'Splashart/RekSai_0.jpg', splashartBig:'Splashart/RekSai_Splash_0.jpg')
Champion.create(name: 'Renekton', lane:'top', quickinfo:'AD bruiser with strong lane presence and a unique Ressource bar rage. High base dmg enables him to build full tank and still dish out respectable dmg', portrait:'Portrait/Renekton_Square_0.png ' , splashart:'Splashart/Renekton_0.jpg', splashartBig:'Splashart/Renekton_Splash_0.jpg')
Champion.create(name: 'Rengar', lane:'top/jungle', quickinfo:'Unique resource ferocity which enhances his abilites everytime its full. Depending on the build can act as assassin or strong backline disruptor', portrait:'Portrait/Rengar_Square_0.png', splashart:'Splashart/Rengar_0.jpg', splashartBig:'Splashart/Rengar_Splash_0.jpg')
Champion.create(name: 'Riven', lane:'top/mid', quickinfo:'AD caster with no resources besides cooldown, high mobility and burst dmg', portrait:'Portrait/Riven_Square_0.png', splashart:'Splashart/Riven_0.jpg', splashartBig:'Splashart/Riven_Splash_0.jpg')
Champion.create(name: 'Rumble', lane:'top', quickinfo:'Melee ap fighter that excels at dealing dmg over time. Unique resource heat can turn his damage over time in high single target burst', portrait:'Portrait/Rumble_Square_0.png', splashart:'Splashart/Rumble_0.jpg', splashartBig:'Splashart/Rumble_Splash_0.jpg')
Champion.create(name: 'Ryze', lane:'mid/top', quickinfo:'Ap carry with one of the highest dps ingame, scales with mana wich enables him to build tank/mana items and still do considerable amount of dmg', portrait:'Portrait/Ryze_Square_0.png', splashart:'Splashart/Ryze_0.jpg', splashartBig:'Splashart/Ryze_Splash_0.jpg')
Champion.create(name: 'Sejuani', lane:'mid/jungle', quickinfo:'AP fighter that can build tanky or burst dmg. Alot of CC capabilites for storng ganks', portrait:'Portrait/Sejuani_Square_0.png', splashart:'Splashart/Sejuani_0.jpg', splashartBig:'Splashart/Sejuani_Splash_0.jpg')
Champion.create(name: 'Shaco', lane:'jungle', quickinfo:'AD Assassin that can go invisible, slow/fear enemies and clone himself with his ult. Strong gank potential in all phases of the game', portrait:'Portrait/Shaco_Square_0.png', splashart:'Splashart/Shaco_0.jpg', splashartBig:'Splashart/Shaco_Splash_0.jpg')
Champion.create(name: 'Shen', lane:'top', quickinfo:'Tank bruiser that can taunt or shield an ally with his ultimate and travel to his position on the map. Strong splitpusher', portrait:'Portrait/Shen_Square_0.png', splashart:'Splashart/Shen_0.jpg', splashartBig:'Splashart/Shen_Splash_0.jpg')
Champion.create(name: 'Shyvana', lane:'top', quickinfo:'Tank/fighter with an Shapeshifting ultimate to transform into a dragon once her ressources bar is full. Strong backline disruptor', portrait:'Portrait/Shyvana_Square_0.png', splashart:'Splashart/Shyvana_0.jpg', splashartBig:'Splashart/Shyvana_Splash_0.jpg')
Champion.create(name: 'Singed', lane:'top', quickinfo:'AP tank with great damage over time and movementspeed to stick to his targets', portrait:'Portrait/Singed_Square_0.png', splashart:'Splashart/Singed_0.jpg', splashartBig:'Splashart/Singed_Splash_0.jpg')
Champion.create(name: 'Sion', lane:'top/jungle', quickinfo:'Bruiser that can build full tank for massive backline disruption or AP for high poke/burst dmg. Strong lvl 6 gank with his ulitamte', portrait:'Portrait/Sion_Square_0.png', splashart:'Splashart/Sion_0.jpg', splashartBig:'Splashart/Sion_Splash_0.jpg')
Champion.create(name: 'Sivir', lane:'adc', quickinfo:'Short range adc but with a long range poke ability. Strong waveclear/pushing power. Ultimate to speed up herself and her team', portrait:'Portrait/Sivir_Square_0.png', splashart:'Splashart/Sivir_0.jpg', splashartBig:'Splashart/Sivir_Splash_0.png')
Champion.create(name: 'Skarner', lane:'jungler', quickinfo:'Tank bruiser with an ultimate to drag enemies into his team for strong initiation/lvl 6 gank', portrait:'Portrait/Skarner_Square_0.png', splashart:'Splashart/Skarner_0.jpg', splashartBig:'Splashart/Skarner_Splash_0.jpg')
Champion.create(name: 'Sona', lane:'support', quickinfo:'Exceptionally squishy support with alot utility for her team and an AOE stun ultimate. Strong laning because of her sustain but prone to all-ins before lvl 6', portrait:'Portrait/Sona_Square_0.png', splashart:'Splashart/Sona_0.jpg', splashartBig:'Splashart/Sona_Splash_0.jpg')
Champion.create(name: 'Soraka', lane:'support', quickinfo:'Healing but with a global ultimate to heal her whole team anywhere on the map', portrait:'Portrait/Soraka_Square_0.png', splashart:'Splashart/Soraka_0.jpg', splashartBig:'Splashart/Soraka_Splash_0.jpg')
Champion.create(name: 'Swain', lane:'top/mid', quickinfo:'AP mage specialized in doing large amounts of dmg over time. Relies on his shapeshifting ultimate which does dmg to surrounding enemies and heals him for a percentage of the dmg dealt', portrait:'Portrait/Swain_Square_0.png', splashart:'Splashart/Swain_0.jpg', splashartBig:'Splashart/Swain_Splash_0.jpg')
Champion.create(name: 'Syndra', lane:'mid', quickinfo:'AP mage with high single target burst. Strong laner', portrait:'Portrait/Syndra_Square_0.png', splashart:'Splashart/Syndra_0.jpg', splashartBig:'Splashart/Syndra_Splash_0.jpg')
Champion.create(name: 'Talon', lane:'mid', quickinfo:'AD assassin with an ulitamte which makes him invisible to easily dive the enemy backline', portrait:'Portrait/Talon_Square_0.png', splashart:'Splashart/Talon_0.jpg', splashartBig:'Splashart/Talon_Splash_0.jpg')
Champion.create(name: 'Taric', lane:'support', quickinfo:'Melee Support with a stun, heal and abilites to buff stats of his teammates and debuff the enemy', portrait:'Portrait/Taric_Square_0.png', splashart:'Splashart/Taric_0.jpg', splashartBig:'Splashart/Taric_Splash_0.jpg')
Champion.create(name: 'Teemo', lane:'mid/top', quickinfo:'Range champion that relies on autohits which scale with ap. Ultimate lets him plant invisible traps around the map which dmg and slow enemies', portrait:'Portrait/Teemo_Square_0.png', splashart:'Splashart/Teemo_0.jpg', splashartBig:'Splashart/Teemo_Splash_0.jpg')
Champion.create(name: 'Thresh', lane:'support', quickinfo:'One of the most versatile Supports. Has a hook to engage, can disengage with his ultimate and a lantern to rescue allies out of position', portrait:'Portrait/Thresh_Square_0.png', splashart:'Splashart/Thresh_0.jpg', splashartBig:'Splashart/Thresh_Splash_0.jpg')
Champion.create(name: 'Tristana', lane:'adc', quickinfo:'Adc whose range increases with her lvl. Strong self peel with a jump that resets on kills, lategame beast', portrait:'Portrait/Tristana_Square_0.png', splashart:'Splashart/Tristana_0.jpg', splashartBig:'Splashart/Tristana_Splash_0.jpg')
Champion.create(name: 'Trundle', lane:'top/jungle', quickinfo:'AD Bruiser with strong sustain. Ultimate steals enemy stats to make him the ultimate tank killer', portrait:'Portrait/Trundle_Square_0.png', splashart:'Splashart/Trundle_0.jpg', splashartBig:'Splashart/Trundle_Splash_0.jpg')
Champion.create(name: 'Tryndamere', lane:'top', quickinfo:'Melee ad carry with an ultimate which makes him immortal for a short amount of time. One of the strongest duelist ingame', portrait:'Portrait/Tryndamere_Square_0.png', splashart:'Splashart/Tryndamere_0.jpg', splashartBig:'Splashart/Tryndamere_Splash_0.jpg')
Champion.create(name: 'TwistedFate', lane:'mid', quickinfo:'AP mage with strong pushing power and CC. Global Ultimate lets him teleport anywhere on the map for strong ganks/roams and splitpushing', portrait:'Portrait/TwistedFate_Square_0.png', splashart:'Splashart/TwistedFate_0.jpg', splashartBig:'Splashart/TwistedFate_Splash_0.jpg')
Champion.create(name: 'Twitch', lane:'adc', quickinfo:'Adc that can go invisible, lets him roam effectivly for strong surprise ganks. Ultimate gives him the highest range in the game and his autoattack pierce through his targets', portrait:'Portrait/Twitch_Square_0.png', splashart:'Splashart/Twitch_0.jpg', splashartBig:'Splashart/Twitch_Splash_0.jpg')
Champion.create(name: 'Udyr', lane:'top/jungle', quickinfo:'High movementspeed tank bruiser with unique set of 4 abilites and no ultimate. Can max out his abilites based on his needs/preferences', portrait:'Portrait/Udyr_Square_0.png', splashart:'Splashart/Udyr_0.jpg', splashartBig:'Splashart/Udyr_Splash_0.jpg')
Champion.create(name: 'Urgot', lane:'top/adc', quickinfo:'AD bruiser with strong long range poke and shreds enemies armor. His ultimate enables him to switch places with a target enemy', portrait:'Portrait/Urgot_Square_0.png', splashart:'Splashart/Urgot_0.jpg', splashartBig:'Splashart/Urgot_Splash_0.jpg')
Champion.create(name: 'Varus', lane:'adc', quickinfo:'Immobile adc with strong poke potential. Ultimate lets him hold targets in place', portrait:'Portrait/Varus_Square_0.png', splashart:'Splashart/Varus_0.jpg', splashartBig:'Splashart/Varus_Splash_0.jpg')
Champion.create(name: 'Vayne', lane:'adc', quickinfo:'Adc that does %-dmg of enemies max health on every third hit. Can go invisible with her ultimate for strong outplay potential, lategame monster', portrait:'Portrait/Vayne_Square_0.png', splashart:'Splashart/Vayne_0.jpg', splashartBig:'Splashart/Vanye_Splash_0.jpg')
Champion.create(name: 'Veigar', lane:'mid', quickinfo:'Ap burst mage that increses his ap with minion kills. Has an AOE stun for strong teamfight impact', portrait:'Portrait/Veigar_Square_0.png', splashart:'Splashart/Veigar_0.jpg', splashartBig:'Splashart/Veigar_Splash_0.jpg')
Champion.create(name: 'VelKoz', lane:'mid/support', quickinfo:'Ap mage with strong poke and CC. Is able to do true dmg with his passive after he hit 3 spells. Ultimate is a constant laser paired with his passive for huge amount of AOE dmg. Low mana cost enables him to be played as support', portrait:'Portrait/VelKoz_Square_0.png', splashart:'Splashart/Velkoz_0.jpg', splashartBig:'Splashart/Velkoz_Splash_0.jpg')
Champion.create(name: 'Vi', lane:'jungle', quickinfo:'Ad bruiser with strong long range engage on a single target and burst', portrait:'Portrait/Vi_Square_0.png', splashart:'Splashart/Vi_0.jpg', splashartBig:'Splashart/Vi_Splash_0.jpg')
Champion.create(name: 'Viktor', lane:'mid', quickinfo:'Ap mage with strong AOE dmg and teamfight control', portrait:'Portrait/Viktor_Square_0.png', splashart:'Splashart/Viktor_0.jpg', splashartBig:'Splashart/Viktor_Splash_0.jpg')
Champion.create(name: 'Vladimir', lane:'mid/top', quickinfo:'Ap mage with no ressources and high sustain. Ultimate enhances dmg against enemies from all sources', portrait:'Portrait/Vladimir_Square_0.png', splashart:'Splashart/Vladimir_0.jpg', splashartBig:'Splashart/Vladimir_Splash_0.jpg')
Champion.create(name: 'Volibear', lane:'jungle/top', quickinfo:'Tank bruiser that scales with HP. Strong engage to catch single enemies out of position and a passive that regenerates his health once he gets lower then 30%', portrait:'Portrait/Volibear_Square_0.png', splashart:'Splashart/Volibear_0.jpg', splashartBig:'Splashart/Volibear_Splash_0.jpg')
Champion.create(name: 'Warwick', lane:'jungle/top', quickinfo:'High sustain tank with an ultimate to suppress a single enemy target for strong lvl 6 ganks', portrait:'Portrait/Warwick_Square_0.png', splashart:'Splashart/Warwick_0.jpg', splashartBig:'Splashart/Warwick_Splash_0.jpg')
Champion.create(name: 'WuKong', lane:'jungle/top', quickinfo:'AD bruiser with strong dmg and an AOE knock up ultimate. His W creates a clone and he goes invisible for a short amount of time giving him great juking potential', portrait:'Portrait/MonkeyKing_Square_0.png', splashart:'Splashart/MonkeyKing_0.jpg', splashartBig:'Splashart/MonkeyKing_Splash_0.jpg')
Champion.create(name: 'Xerath', lane:'mid', quickinfo:'Long range ap mage with strong poke and high pushing/sieging power. Global ultimate to snipe/pick off fleeing enemies', portrait:'Portrait/Xerath_Square_0.png', splashart:'Splashart/Xerath_0.jpg', splashartBig:'Splashart/Xerath_Splash_0.jpg')
Champion.create(name: 'XinZhao', lane:'top/jungle', quickinfo:'Melee ad carry with high sustain and knock up/knock back abilites. Gapcloser that slows the target for strong early ganks', portrait:'Portrait/XinZhao_Square_0.png', splashart:'Splashart/XinZhao_0.jpg', splashartBig:'Splashart/XinZhao_Splash_0.jpg')
Champion.create(name: 'Yasuo', lane:'mid', quickinfo:'Melee ad carry with a unique ability Windwall which block all incoming projectiles. Unique ressources flow, which generates a shield on the next incoming dmg once its full. Ultimate CC knocked up targets', portrait:'Portrait/Yasuo_Square_0.png', splashart:'Splashart/Yasuo_0.jpg', splashartBig:'Splashart/Yasuo_Splash_0.jpg')
Champion.create(name: 'Yorick', lane:'top', quickinfo:'Melee Tank/Fighter that summons ghouls which fight for him and give him unique effects. High sustain and an ultimate that clones an ally revives him for a short amount of time', portrait:'Portrait/Yorick_Square_0.png', splashart:'Splashart/Yorick_0.jpg', splashartBig:'Splashart/Yorick_Splash_0.jpg')
Champion.create(name: 'Zac', lane:'top/jungle', quickinfo:'Tank that uses his HP as resource for his abilites. Drops blobs that he can pick up to get HP back. Strong long range engage', portrait:'Portrait/Zac_Square_0.png', splashart:'Splashart/Zac_0.jpg', splashartBig:'Splashart/Zac_Splash_0.jpg')
Champion.create(name: 'Zed', lane:'mid', quickinfo:'AD assassin with high mobility to blow up single targets without exposing himself completly', portrait:'Portrait/Zed_Square_0.png', portrait:'Portrait/Zed_Square_0.png', splashart:'Splashart/Zed_0.jpg', splashartBig:'Splashart/Zed_Splash_0.jpg' )
Champion.create(name: 'Ziggs', lane:'mid', quickinfo:'Long range ap mage with strong zone control and poke. Global AOE ultimate to blow up entire teams anywhere on the map', portrait:'Portrait/Ziggs_Square_0.png', splashart:'Splashart/Ziggs_0.jpg', splashartBig:'Splashart/Ziggs_Splash_0.jpg')
Champion.create(name: 'Zilean', lane:'support', quickinfo:'Support with strong utility, can seepd up allies, slow/stun enemies and revive his allies with his ultimate', portrait:'Portrait/Zilean_Square_0.png', splashart:'Splashart/Zilean_0.jpg', splashartBig:'Splashart/Zilean_Splash_0.jpg')
Champion.create(name: 'Zyra', lane:'support/mid', quickinfo:'Ap mage that summons plants to fight for her. Can root enemies in place and has an ulimate to knock up multiple enemies in an area which makes for a strong support', portrait:'Portrait/Zyra_Square_0.png', splashart:'Splashart/Zyra_0.jpg', splashartBig:'Splashart/Zyra_Splash_0.jpg' )



#items
# Item.create(name: "", info:"", image:"items/")
Item.create(name: 'Abyssal Scepter', info:'ap/mr', image:'items/', cost:"2440 (730)",info:"+70 Ability Power|+50 Magic Resist|UNIQUE Aura: Reduces the Magic Resist of nearby enemies by 20.")
Item.create(name: 'Aegis of the Legion', info:'health/hreg/mr/armor', image:'items/Aegis_of_the_Legion_item.png', cost:"1900 (820)", info:"+200 Health|+20 Magic Resistance|UNIQUE Aura - Legion: Grants nearby allies +20 Magic Resist and +75% Base Health Regen.|(Unique Auras with the same name don't stack.)|")
Item.create(name: 'Aether Wisp', info:'ms/ap', image:'items/Aether_Wisp_item.png', cost:"850 (415)", info:"+30 Ability Power|UNIQUE Passive: +5% Movement Speed")
Item.create(name: 'Amplifying Tome', info:'ap', image:'items/Amplifying_Tome_item.png', cost:"435 (435)", info:"+20 Ability Power")
Item.create(name: 'Ancient Coin', info:'gp5/mreg', image:'items/Ancient_Coin_item.png1', cost:"365 (365)", info:"+25% Base Mana Regen|UNIQUE Passive - Favor: Being near a minion death without dealing the killing blow grants 2 Gold and 5 Health.|Limited to 1 Gold Income item|''Gold dust rises from the desert and clings to the coin.'' - Historian Shurelya, 11 November, 23 CLE|")
Item.create(name: 'Ardent Censor', info:'ap/ms', image:'items/Ardent_Censer_item.png')
Item.create(name: 'Skirmishers Sabre', info:'nil', image:'items/3714_skirmishers_Sabre.jpg')
Item.create(name: "Archangel's Staff", info:'mana/ap', image:"items/Archangel's_Staff_item.png")
Item.create(name: "Athene's Unholy Grail", info:'mreg/ap/mr', image:"items/Athene's_Unholy_grail_item.png")
Item.create(name: "Atma's Impaler", info:"armor/ad/crit", image:"items/Atma's_Impaler_item.png")
Item.create(name: "Averice Blade", info:"gp5/crit", image:"items/Averice_Blade_item.png")
Item.create(name: "Banner of Command", info:"ap/cdr", image:"items/Banner_of_Command_item.png")
Item.create(name: "Banshee's Veil", info:"health/mr", image:"items/Banshee's_Veil_item.png")
Item.create(name: "Berserker's Greaves Alacrity", info:"as/ms", image:"items/Berserker's_Greave_Alacrity_item.png")
Item.create(name: "Berserker's Greaves Captain", info:"as/ms", image:"items/Berserker's_Greave_Captain_item.png")
Item.create(name: "Berserker's Greaves Distortion", info:"as/ms", image:"items/Berserker's_Greave_Distortion_item.png")
Item.create(name: "Berserker's Greaves Furor", info:"as/ms", image:"items/Berserker's_Greave_Furor_item.png")
Item.create(name: "Berserker's Greaves", info:"as/ms", image:"items/Berserker's_Greaves.gif")
Item.create(name: "BF Sword", info:"ad", image:"items/B._F._Sword_item.png")
Item.create(name: "Bilgewater Cutlass", info:"ls/ad", image:"items/Bilgewater_Cutlass_item.png")
Item.create(name: "Blade of the Ruined King", info:"as/ad/ls", image:"items/Blade_of_the_ruined_king_item.png")
Item.create(name: "Blasting Wand", info:"ap", image:"items/Blasting_Wand_item.png")
Item.create(name: "Bonetooth Necklace Blue (12 Trophies)", info:"rengar", image:"items/Bonetooth_Necklace_(Blue)_(12_Trophies)_item.png")
Item.create(name: "Bonetooth Necklace Blue (20 Trophies)", info:"rengar", image:"items/Bonetooth_Necklace_(Blue)_(20_Trophies)_item.png")
Item.create(name: "Bonetooth Necklace Blue (3 Trophies)", info:"rengar", image:"items/Bonetooth_Necklace_(Blue)_(3_Trophies)_item.png")
Item.create(name: "Bonetooth Necklace Blue (6 Trophies)", info:"rengar", image:"items/Bonetooth_Necklace_(Blue)_(6_Trophies)_item.png")
Item.create(name: "Bonetooth Necklace Blue", info:"rengar", image:"items/Bonetooth_Necklace_(Blue)_item.png")
Item.create(name: "Bonetooth Necklace Green (12 Trophies)", info:"rengar", image:"items/Bonetooth_Necklace_(Green)_(12_Trophies)_item.png")
Item.create(name: "Bonetooth Necklace Green (20 Trophies)", info:"rengar", image:"items/Bonetooth_Necklace_(Green)_(20_Trophies)_item.png")
Item.create(name: "Bonetooth Necklace Green (3 Trophies)", info:"rengar", image:"items/Bonetooth_Necklace_(Green)_(3_Trophies)_item.png")
Item.create(name: "Bonetooth Necklace Green (6 Trophies)", info:"rengar", image:"items/Bonetooth_Necklace_(Green)_(6_Trophies)_item.png")
Item.create(name: "Bonetooth Necklace Green", info:"rengar", image:"items/Bonetooth_Necklace_(Green)_item.png")
Item.create(name: "Bonetooth Necklace Red (12 Trophies)", info:"rengar", image:"items/Bonetooth_Necklace_(Red)_(12_Trophies)_item.png")
Item.create(name: "Bonetooth Necklace Red (20 Trophies)", info:"rengar", image:"items/Bonetooth_Necklace_(Red)_(20_Trophies)_item.png")
Item.create(name: "Bonetooth Necklace Red (3 Trophies)", info:"rengar", image:"items/Bonetooth_Necklace_(Red)_(3_Trophies)_item.png")
Item.create(name: "Bonetooth Necklace Red (6 Trophies)", info:"rengar", image:"items/Bonetooth_Necklace_(Red)_(6_Trophies)_item.png")
Item.create(name: "Bonetooth Necklace Red", info:"rengar", image:"items/Bonetooth_Necklace_(Red)_item.png")
Item.create(name: "Bonetooth Necklace Yellow (12 Trophies)", info:"rengar", image:"items/Bonetooth_Necklace_(Yellow)_(12_Trophies)_item.png")
Item.create(name: "Bonetooth Necklace Yellow (20 Trophies)", info:"rengar", image:"items/Bonetooth_Necklace_(Yellow)_(20_Trophies)_item.png")
Item.create(name: "Bonetooth Necklace Yellow (3 Trophies)", info:"rengar", image:"items/Bonetooth_Necklace_(Yellow)_(3_Trophies)_item.png")
Item.create(name: "Bonetooth Necklace Yellow (6 Trophies)", info:"rengar", image:"items/Bonetooth_Necklace_(Yellow)_(6_Trophies)_item.png")
Item.create(name: "Bonetooth Necklace Yellow", info:"rengar", image:"items/Bonetooth_Necklace_(Yellow)_item.png")
Item.create(name: "Boots of Mobility Alacrity", info:"ms", image:"items/Boots_of_Mobility_Alacrity_item.png")
Item.create(name: "Boots of Mobility Captain", info:"ms", image:"items/Boots_of_Mobility_Captain_item.png")
Item.create(name: "Boots of Mobility Distortion", info:"ms", image:"items/Boots_of_Mobility_Distortion_item.png")
Item.create(name: "Boots of Mobility Furor", info:"ms", image:"items/Boots_of_Mobility_Furor_item.png")
Item.create(name: "Boots of Mobility Homeguard", info:"ms", image:"items/Boots_of_Mobility_Homeguard_item.png")
Item.create(name: "Boots of Mobility", info:"ms", image:"items/Boots_of_Mobility_item.png")
Item.create(name: "Boots of Speed", info:"ms", image:"items/Boots_of_Speed_item.png")
Item.create(name: "Boots of Swiftness Alacrity", info:"ms", image:"items/Boots_of_Swiftness_Alacrity_item.png")
Item.create(name: "Boots of Swiftness Captain", info:"ms", image:"items/Boots_of_Swiftness_Captain_item.png")
Item.create(name: "Boots of Swiftness Distortion", info:"ms", image:"items/Boots_of_Swiftness_Distortion_item.png")
Item.create(name: "Boots of Swiftness Furor", info:"ms", image:"items/Boots_of_Swiftness_Furor_item.png")
Item.create(name: "Boots of Swiftness Homeguard", info:"ms", image:"items/Boots_of_Swiftness_Homeguard_item.png")
Item.create(name: "Boots of Swiftness", info:"ms", image:"items/Boots_of_Swiftness_item.png")
Item.create(name: "Brawler's Gloves", info:"crit", image:"items/Brawler's_Gloves_item.png")
Item.create(name: "Catalyst the Protector", info:"mana/health", image:"items/Catalyst_the_Protector_item.png")
Item.create(name: "Chain Vest", info:"armor", image:"items/Chain_Vest_item.png")
Item.create(name: "Chalice of Harmony", info:"mr/mreg", image:"items/Chalice_of_Harmony_item.png")
Item.create(name: "Cloak of Agility", info:"crit", image:"items/Cloak_of_Agility_item.png")
Item.create(name: "Cloth Armor", info:"armor", image:"items/Cloth_Armor_item.png")
Item.create(name: "Crystalline Bracer", info:"hreg/health", image:"items/Crystalline_Bracer_item.png")
Item.create(name: "Crystalline Flask", info:"pot", image:"items/Crystalline_Flask_item.png")
Item.create(name: "Dagger", info:"as", image:"items/Dagger_item.png")
Item.create(name: "Defaultitem", info:"default", image:"items/DefaultItem.gif")
Item.create(name: "Doran's Blade", info:"ad/ls", image:"items/Doran's_Blade.gif")
Item.create(name: "Doran's Ring", info:"ap/mreg", image:"items/Doran's_Ring_item.png")
Item.create(name: "Doran's Shield", info:"health", image:"items/Doran's_Shield_item.")
Item.create(name: "Elixir of Iron", info:"pot", image:"items/Elixir_of_Iron_item.png")
Item.create(name: "Elixir of Ruin", info:"pot", image:"items/Elixir_of_Ruin_item.png")
Item.create(name: "Elixir of Sorcery", info:"pot", image:"items/Elixir_of_Sorcery_item.png")
Item.create(name: "Elixir of Wrath", info:"pot", image:"items/Elixir_of_Wrath_item.png")
Item.create(name: "Essence Reaver", info:"ad/cdr/ls", image:"items/Essence_Reaver_item.png")
Item.create(name: "Executioner's Calling", info:"as/crit", image:"items/Executioner's_Calling_item.png")
Item.create(name: "Explorer's Ward", info:"ward", image:"items/Explorer's_Ward_item.png")
Item.create(name: "Face of the Mountain", info:"health/hreg", image:"items/Face_of_the_Moutain_item.png")
Item.create(name: "Faerie Charm", info:"mreg", image:"items/Faerie_Charm_item.png")
Item.create(name: "Farsight Orb", info:"trinket", image:"items/Farsight_Orb_item.jpg")
Item.create(name: "Fiendish Codex", info:"ap/cdr", image:"items/Fiendish_Codex_item.png")
Item.create(name: "Forbidden Idol", info:"mreg", image:"items/Forbidden_Idol_item.png")
Item.create(name: "Frost Queen's Claim", info:"ap/mreg/gp5", image:"items/Frost_Queen's_Claim_item.png")
Item.create(name: "Frostfang", info:"ap/mreg/gp5", image:"items/Frostfang_item.jpg")
Item.create(name: "Frozen Heart", info:"armor/cdr/mana", image:"items/Frozen_Heart_item.png")
Item.create(name: "Frozen Mallet", info:"ad/health/slow", image:"items/Frozen_Mallet_item.png")
Item.create(name: "Giant's Belt", info:"health", image:"items/Giant's_Belt_item.png")
Item.create(name: "Glacial Shroud", info:"armor", image:"items/Glacial_Shroud_item.png")
Item.create(name: "Greater Lens", info:"trinket", image:"items/Greater_Lens_item.png")
Item.create(name: "Greater Orb", info:"trinket", image:"items/Greater_Orb_item.jpg") 
Item.create(name: "Greater Stealth Totem", info:"trinket", image:"items/Greater_Stealth_Totem_item.jpg")
Item.create(name: "Greater Totem", info:"trinket", image:"items/Greater_Vision_Totem_item.jpg")
Item.create(name: "Guardian Angel", info:"mr/armor", image:"items/Guardian_Angel_item.png")
Item.create(name: "Guinsoo's Rageblade", info:"as/ad/ap", image:"items/Guinsoo's_Rageblade_item.png")
Item.create(name: "Hexdrinker_item.png", info:"ad/mr", image:"items/Hexdrinker_item.png")
Item.create(name: "Hextech Gunblade", info:"ls/sv/ap/ad", image:"items/Hextech_Gunblade_item.png")
Item.create(name: "Hextech Revolver", info:"sv/ap", image:"items/Hextech_Revolver_item.png")
Item.create(name: "Hunter's Machete", info:"jungle", image:"items/Hunter's_Machete_item.png")
Item.create(name: "Iceborn Gauntlet", info:"armor/ap/mana/slow", image:"items/Iceborn_Gauntlet_item.png")
Item.create(name: "Infinity Edge", info:"ad/crit", image:"items/Infinity_Edge_item.png")
Item.create(name: "Ionian Boots Alacrity", info:"ms", image:"items/Ionian_Boots_of_Lucidity_Alacrity_item.png")
Item.create(name: "Ionian Boots Captain", info:"ms", image:"items/Ionian_Boots_of_Lucidity_Captain_item.png")
Item.create(name: "Ionian Boots Distortion", info:"ms", image:"items/Ionian_Boots_of_Lucidity_Distortion_item.png")
Item.create(name: "Ionian Boots Furor", info:"ms", image:"items/Ionian_Boots_of_Lucidity_Furor_item.png")
Item.create(name: "Ionian Boots Homeguard", info:"ms", image:"items/Ionian_Boots_of_Lucidity_Homeguard_item.png")
Item.create(name: "Ionian Boots", info:"ms", image:"items/Ionian_Boots_of_Lucidity_item.png")
Item.create(name: "Kindlegem", info:"health/cdr", image:"items/Kindlegem_item.png")
Item.create(name: "Last Whisper", info:"apen/ad", image:"items/Last_Whisper_item.png")
Item.create(name: "Liandry's Torment", info:"mpen/ap/health", image:"items/Liandry's_Torment_item.png")
Item.create(name: "Lich Bane", info:"ap/ms/mana", image:"items/Lich_Bane_item.png")
Item.create(name: "Locket of the Iron Solari", info:"cdr/health/mr/armor/cdr", image:"items/Locket_of_the_Iron_Solari_item.png")
Item.create(name: "Long Sword", info:"ad", image:"items/Long_Sword_item.png")
Item.create(name: "Luden's Echo", info:"ap", image:"items/Luden's_Echo_item.png")
Item.create(name: "Mana Potion", info:"pot", image:"items/Mana_Potion_item.png")
Item.create(name: "Manamune", info:"ad/mana", image:"items/Manamune_item.png")
Item.create(name: "Maw of Malmortius", info:"ad/mr", image:"items/Maw_of_Malmortius_item.png")
Item.create(name: "Mejai's Soulstealer", info:"ap/cdr", image:"items/Meja's_Soulstealer_item.png")
Item.create(name: "Mercury's Treads Alacrity", info:"ms/mr", image:"items/Mercury_Treads_Alacrity_item.png")
Item.create(name: "Mercury's Treads Captain", info:"ms/mr", image:"items/Mercury_Treads_Captain_item.png")
Item.create(name: "Mercury's Treads Distortion", info:"ms/mr", image:"items/Mercury_Treads_Distortion_item.png")
Item.create(name: "Mercury's Treads Furor", info:"ms/mr", image:"items/Mercury_Treads_Furor_item.png")
Item.create(name: "Mercury's Treads Homeguard", info:"ms/mr", image:"items/Mercury_Treads_Homeguard_item.png")
Item.create(name: "Mercury's Treads", info:"ms/mr", image:"items/Mercury_Treads_item.png")
Item.create(name: "Mikael's Crucible", info:"mreg/mr", image:"items/Mikael's_Crucible_item.png")
Item.create(name: "Morellonomicon", info:"ap/cdr/mreg", image:"items/Morellonomicon_item.png")
Item.create(name: "Muramana", info:"ad/mana", image:"items/Muramana_item.png")
Item.create(name: "Nashor's Tooth", info:"as/ap", image:"items/Nashor's_Tooth_item.png")
Item.create(name: "Needlessly Large Rod", info:"ap", image:"items/Needlessly_Large_Rod_item.png")
Item.create(name: "Negatron Cloak", info:"mr", image:"items/Negatron_Cloak_item.png")
Item.create(name: "Ninja Tabi Alacrity", info:"ms", image:"items/Ninja_Tabi_Alacrity_item.png")
Item.create(name: "Ninja Tabi Captain", info:"ms", image:"items/Ninja_Tabi_Captain_item.png")
Item.create(name: "Ninja Tabi Distortion", info:"ms", image:"items/Ninja_Tabi_Distortion_item.png")
Item.create(name: "Ninja Tabi Furor", info:"ms", image:"items/Ninja_Tabi_Furor_item.png")
Item.create(name: "Ninja Tabi Homeguard", info:"ms", image:"items/Ninja_Tabi_Homeguard_item.png")
Item.create(name: "Ninja Tabi", info:"ms", image:"items/Ninja_Tabi_item.png")
Item.create(name: "Nomad's Medaillon", info:"mreg/gp5", image:"items/Nomad's_Medallion_item.png")
Item.create(name: "Null Magic Mantle", info:"mr", image:"items/Null-Magic_Mantle_item.png")
Item.create(name: "Ohmwrecker", info:"health/mana", image:"items/Ohmwrecker_item.png")
Item.create(name: "Oracle's Lens", info:"trinket", image:"items/Oracle's_Lens_item.jpg")
Item.create(name: "Perfect Hex Core", info:"viktor", image:"items/Perfect_Hex_Core_item.png")
Item.create(name: "Phage", info:"ad/health", image:"items/Phage.gif")
Item.create(name: "Phantom Dancer", info:"as/crit", image:"items/Phantom_Dancer_item.png")
Item.create(name: "Pickaxe", info:"ad", image:"items/Pickaxe_item.png")
Item.create(name: "Poacher's Knife", info:"jungle", image:"items/Poacher's_Knife_item.png")
Item.create(name: "Poacher's Knife Devourer", info:"jungle", image:"items/Poacher's_Knife_(Devourer)_item.png")
Item.create(name: "Poacher's Knife Juggernaut", info:"jungle", image:"items/Poacher's_Knife_(Juggernaut)_item.png")
Item.create(name: "Poacher's Knife Magus", info:"jungle", image:"items/Poacher's_Knife_(Magus)_item.png")
Item.create(name: "Poacher's Knife Warrior", info:"jungle", image:"items/Poacher's_Knife_(Warrior)_item.png")
Item.create(name: "Prototyp Hex Core", info:"viktor", image:"items/Prototype_Hex_Core_item.png")
Item.create(name: "Quicksilver Sash", info:"mr", image:"items/Quicksilver_Sash_item.png")
Item.create(name: "Quill Coat", info:"health/armor", image:"items/Quill_Coat_item.png")
Item.create(name: "Rabadon's Deathcap", info:"ap", image:"items/Rabadon's_Deathcap_item.png")
Item.create(name: "Randuin's Omen", info:"health/armor", image:"items/Randuins's_Omen_item.png")
Item.create(name: "Ranger's Trailblazer", info:"jungle", image:"items/Ranger's_Trailblazer_item.png")
Item.create(name: "Ranger's Trailblazer Devourer", info:"jungle", image:"items/Ranger's_Trailblazer_(Devourer)_item.png")
Item.create(name: "Ranger's Trailblazer Juggernaut", info:"jungle", image:"items/Ranger's_Trailblazer_(Juggernaut)_item.png")
Item.create(name: "Ranger's Trailblazer Magus", info:"jungle", image:"items/Ranger's_Trailblazer_(Magus)_item.png")
Item.create(name: "Ranger's Trailblazer Warrior", info:"jungle", image:"items/Ranger's_Trailblazer_(Warrior)item.png")
Item.create(name: "Ravenous Hydra", info:"ad/hreg/ls", image:"items/Ravenous_Hydra_item.png")
Item.create(name: "Reaper's Emblem", info:"health/gp5", image:"items/Reaper's_Emblem_item.png")
Item.create(name: "Recurve Bow", info:"as", image:"items/Recurve_Bow_item.png")
Item.create(name: "Rejuvenation Bead", info:"hreg", image:"items/Rejuvenation_Bead_item.png")
Item.create(name: "Relic Shield", info:"health/hreg", image:"items/Relic_Shield_item.png")
Item.create(name: "Righteous Glory", info:"mana/health", image:"items/Righteous_Glory_item.png")
Item.create(name: "Rod of Ages", info:"ap/mana/health", image:"items/Rod_of_Ages_item.png")
Item.create(name: "Ruby Crystal", info:"health", image:"items/Ruby_Crystal_item.png")
Item.create(name: "Ruby Sightstone", info:"health", image:"items/Ruby_Sightstone_item.png")
Item.create(name: "Runaan's Hurrican", info:"as", image:"items/Runaan's_Hurrican_item.png")
Item.create(name: "Rylai's Crystal Scepter", info:"health/ap/slow", image:"items/Rylai's_Crystal_Scepter_item.png")
Item.create(name: "Sapphire Crystal", info:"mana", image:"items/Sapphire_Crystal_item.png")
Item.create(name: "Scrying Orb", info:"trinket", image:"items/Scrying_Orb_item.png")
Item.create(name: "Seeker's Armuard", info:"armor/ap", image:"items/Seeker's_Armguard_item.png")
Item.create(name: "Seraph's Embrance", info:"ap/mana", image:"items/Seraph's_Embrance_item.png")
Item.create(name: "Sheen", info:"mana/ap", image:"items/Sheen_item.png")
Item.create(name: "Sightstone_item.png", info:"health", image:"items/Sightstone_item.png")
Item.create(name: "Sight Ward", info:"ward", image:"items/Sight_Ward.gif")
Item.create(name: "Skirmisher's Saber", info:"jungle", image:"items/Skirmisher's_Sabre_item.png")
Item.create(name: "Skirmisher's Saber Devourer", info:"jungle", image:"items/Skirmisher's_Sabre_(Devourer)_item.png")
Item.create(name: "Skirmisher's Saber Juggernaut", info:"jungle", image:"items/Skirmisher's_Sabre_(Juggernaut)_item.png")
Item.create(name: "Skirmisher's Saber Magus", info:"jungle", image:"items/Skirmisher's_Sabre_(Magus)_item.png")
Item.create(name: "Skirmisher's Saber Warrior", info:"jungle", image:"items/Skirmisher's_(Warrior)_Sabre_item.png")
Item.create(name: "Sorcerer's Shoes", info:"mpen/ms", image:"items/Sorcerer's_Shoes_item.png")
Item.create(name: "Sorcerer's Shoes Alacrity", info:"mpen/ms", image:"items/Sorcerer's_Shoes_Alacrity_item.png")
Item.create(name: "Sorcerer's Shoes Distortion", info:"mpen/ms", image:"items/Sorcerer's_Shoes_Distortion_item.png")
Item.create(name: "Sorcerer's Shoes Furor", info:"mpen/ms", image:"items/Sorcerer's_Shoes_Furor_item.png")
Item.create(name: "Sorcerer's Shoes Homeguard", info:"mpen/ms", image:"items/Sorcerer's_Shoes_Homeguard_item.png")
Item.create(name: "Spectre's Cowl", info:"health/mr", image:"items/Spectre's_Cowl.png")
Item.create(name: "Spellthief's Edge", info:"ap/gp5/mreg", image:"items/Spellthief's_Edge_item.png")
Item.create(name: "Spirit Visage", info:"mr/health/cdr", image:"items/Spirit_Visage_item.png")
Item.create(name: "Stalker's Blade", info:"jungle", image:"items/Stalker's_Blade_item.png")
Item.create(name: "Stalker's Blade Devourer", info:"jungle", image:"items/Stalker's_Blade_(Devourer)_item.png")
Item.create(name: "Stalker's Blade Juggernaut", info:"jungle", image:"items/Stalker's_Blade_(Juggernaut)_item.png")
Item.create(name: "Stalker's Blade Magus", info:"jungle", image:"items/Stalker's_Blade_(Magus)_item.png")
Item.create(name: "Stalker's Blade Warrior", info:"jungle", image:"items/Stalker's_Blade_(Warrior)_item.png")
Item.create(name: "Statikk Shiv", info:"as/crit", image:"items/Statikk_Shiv_item.png")
Item.create(name: "Stinger", info:"as/cdr", image:"items/Stinger_item.png")
Item.create(name: "Sunfire Cape", info:"health/armor", image:"items/Sunfire_Cape_item.png")
Item.create(name: "Sweeping Lens", info:"trinket", image:"items/Sweeping_Lens_item.png")
Item.create(name: "Sword of the Divine", info:"as/crit", image:"items/Sword_of_the_Divine_item.png")
Item.create(name: "Sword of the Occult", info:"ad", image:"items/Sword_of_the_Occult_item.png")
Item.create(name: "Talisman of Ascension", info:"mreg/hreg/cdr/gp5", image:"items/Talisman_of_Ascension_item.png")
Item.create(name: "Tear of the Goddess", info:"mana", image:"items/Tear_of_the_Goddess_item.png")
Item.create(name: "The Black Cleaver", info:"apen/health/cdr/ad", image:"items/The_Black_Cleaver_item.png")
Item.create(name: "The Black Spear", info:"kalista", image:"items/The_Black_Spear_item.png")
Item.create(name: "The Bloodthirster", info:"ad/ls", image:"items/The_Bloodthirster_item.png")
Item.create(name: "The Brutalizer", info:"ad/apen", image:"items/The_Brutalizer_item.png")
Item.create(name: "The Hex Core 1", info:"viktor", image:"items/The_Hex_Core_mk-1_item.png")
Item.create(name: "The Hex Core 2", info:"viktor", image:"items/THe_Hex_Core_mk-2_item.png")
Item.create(name: "Thornmail", info:"armor", image:"items/Thornmail_item.png")
Item.create(name: "Tiamat", info:"hreg/ad", image:"items/Tiamat_item.png")
Item.create(name: "Total Biscuit of Rejuvenation", info:"pot", image:"items/Total_Biscuit_of_Rejuvenation_item.png")
Item.create(name: "Trinity Fore", info:"as/ad/health/mana/ap/crit", image:"items/Trinity_FOrce_item.png")
Item.create(name: "Twin Shadows", info:"mr/ap/cdr", image:"items/Twin_Shadows_item.png")
Item.create(name: "Vampiric Scepter", info:"ls/ad", image:"items/Vampiric_Scepter_item.png")
Item.create(name: "Vision Ward", info:"ward", image:"items/Vision_Ward_item.png")
Item.create(name: "Void Staff", info:"ap/mpen", image:"items/Void_Staff_item.png")
Item.create(name: "Warden's Mail", info:"armor", image:"items/Warden's_Mail_item.png")
Item.create(name: "Warding Totem", info:"trinket", image:"items/Warding_Totem_item.jpg")
Item.create(name: "Warmog's Armor", info:"health/hreg", image:"items/Warmog's_Armor.gif")
Item.create(name: "Will of the Ancients", info:"sv/cdr/ap", image:"items/Will_of_the_Ancients_item.png")
Item.create(name: "Wit's End", info:"as/mr", image:"items/Wit's_End_item.png")
Item.create(name: "Youmuu's Ghostblade", info:"as/ad/apen", image:"items/Youmuu's_Ghostblade_item.png")
Item.create(name: "Zeal", info:"as/crit", image:"items/Zeal_item.png")
Item.create(name: "Zeke's Herald", info:"ad/ls", image:"items/Zeke's_Herald_item.png")
Item.create(name: "Zephyir", info:"as/ad", image:"items/Zephyir_item.png")
Item.create(name: "Zhonya's Hourglass", info:"armor/ap", image:"items/Zhonya's_Hourglass_item.png")